# ======================== Measures ========================
measures:
  environmental:
    # []
    - n_agents
    # - n_plants
  immediate:
    []
    # - do_action_eat
  state: []
  behavior: []

aggregators_lifespan:
  []

aggregators_population:
  []



# ======================== Video parameters ========================
config_video:
  do_video : True
  n_steps_per_video : 100
  fps_video : 20
  dir_videos : logs
  height_max_video : 500
  width_max_video : 500
  dict_name_channel_to_color_tag:
    "sun" : "yellow"
    "plants" : "green"
    "agents" : "blue"
  color_background : "gray"